version: '3'

services:
  api:
    build: Api
    ports:
      - "8080:80"
      - "8044:443"
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=value
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      